In [1]:
import numpy as np
import pandas
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import model_selection
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.ensemble import VotingClassifier

In [2]:
url = 'https://github.com/DataQuests/Pandas/raw/master/with_cpep.csv'
df = pandas.read_csv(url)

In [2]:
df = pandas.read_csv("withRatio.csv")
#X = df[['age_bl', 'fma', 'ffma', 'GENDER', 'B meanumb', 'B temp', 'WhtR', 'AGE_WhtR']]
X = df[['ffma', 'GENDER', 'B meanwst', 'B meanumb', '1 clinwt', 'AGE_WhtR']]
y = df['cat ']

In [3]:
df.head(5)

deidnum  GENDER  age_bl  age_3  age_6  age_9  age_12  age_18  age_24  \
0     1057       0   42.01  42.43  42.68  42.93   43.18   43.68   44.18   
1     2081       0   39.21  39.60  39.85  40.10   40.35   40.85   41.35   
2     2230       0   40.56  40.92  41.17  41.42   41.67   42.17   42.67   
3     2355       0   26.83  27.30  27.55  27.80   28.05   28.55   29.05   
4     2373       0   25.79  26.18  26.43  26.68   26.93   27.43   27.93   

        fma  ...   12 WhtR   18 WhtR   24 WhtR  WhtR  WhtR 6  WhtR 12  \
0  18.44968  ...  0.477481  0.463935  0.430071     2       1        1   
1  25.62774  ...  0.486815  0.475225  0.472327     2       1        2   
2  26.45387  ...  0.467144  0.473373  0.445344     2       1        1   
3  30.86636  ...  0.489784  0.470252  0.509315     2       1        2   
4  22.65525  ...  0.498423  0.503155  0.504732     2       2        2   

   WhtR 18  WhtR 24   AGE/BMI   AGE_WhtR  
0        1        1  1.757850  23.473256  
1        1        1  1.564905  20.252632  
2        1        1  1.530727  20.147369  
3        1        2  0.991849  14.007541  
4        2        2  1.013932  13.118728  

[5 rows x 141 columns]

In [142]:
df.shape

(107, 141)

In [148]:
#RFE features
col = ['age_bl', 'fma', 'ffma', 'GENDER', 'B meanumb', 'B meanwst', 'B temp', 'WhtR', 'AGE_WhtR', 'BMI']
#cross validated RFE features (works)
#col = ['age_bl', 'fma', 'ffma', 'GENDER', 'B meanumb', 'B temp', 'WhtR', 'AGE_WhtR']
#correlation mapping
#col = ['ffma', 'GENDER', 'B meanwst', 'B meanumb', '1 clinwt', 'AGE_WhtR']
#Phik correlation mapping
#col = ['B meanwst', 'B meanumb', 'bmi', 'ffma', 'GENDER']
#univariate feature
#col = ['ffma', 'GENDER', 'B meanwst', 'B meanumb', '1 clinwt', 'AGE_WhtR', 'B meansbp', 'age_bl', 'B meanbp', 'fma']
#Extra Tree classifiers
#col = ['GENDER', 'fma', 'B temp', 'B meanumb', 'B pulse', 'ffma', 'B meandbp', '1 clinwt', 'AGE_WhtR', 'B meanwst']
X1 = df[col] 
y1 = df['cat ']

In [149]:
X1

GENDER       fma  B temp  B meanumb  B pulse      ffma  B meandbp  \
0         0  18.44968   36.80     82.500     64.5  33.20032  67.000000   
1         0  25.62774   36.70     89.125     61.0  48.72226  64.166667   
2         0  26.45387   36.60     79.750     73.0  41.09613  83.500000   
3         0  30.86636   36.85     86.875     82.0  43.43364  74.833333   
4         0  22.65525   36.70     80.625     65.0  41.19475  70.000000   
5         0  28.67226   36.85     91.625     68.0  45.57774  65.166667   
6         0  22.35399   36.55     87.375     67.5  45.39601  71.666667   
7         1  16.03920   37.20     82.800     59.5  54.61080  72.000000   
8         0  32.44627   36.75     84.375     79.0  39.75373  80.666667   
9         0  16.93972   36.60     65.750     64.0  39.38528  76.500000   
10        0  19.89859   36.55     82.250     54.0  45.15141  77.500000   
11        0  20.75006   36.30     90.625     67.0  39.82494  66.666667   
12        0  29.01078   36.85     86.375     73.0  44.93922  73.333333   
13        1  19.23703   36.55     90.875     57.0  56.93797  66.666667   
14        0  28.56019   36.85     91.250     61.0  44.23981  66.166667   
15        1  23.34864   36.55     91.375     51.0  55.80136  71.166667   
16        0  23.45835   37.15     85.125     60.5  40.49165  77.333333   
17        0  22.77217   37.05     90.375     69.5  45.05283  66.833333   
18        0  19.87719   36.85     79.000     61.5  46.72281  72.166667   
19        0  18.44139   36.65     83.500     61.5  37.35861  74.333333   
20        0  21.39711   36.55     77.375     53.5  43.40289  60.833333   
21        1  20.37286   36.60     86.375     71.0  52.55214  73.833333   
22        0  24.54634   36.65     82.750     75.5  42.94116  72.000000   
23        1  16.69572   36.55     88.875     64.0  61.60428  75.166667   
24        0  21.80115   36.85     82.750     68.5  46.54885  71.000000   
25        1  27.74827   37.00    102.975     76.5  61.75173  81.000000   
26        0  22.74039   36.90     81.750     70.0  45.38461  67.333333   
27        1  25.11309   36.45    101.000     59.0  66.13691  67.166667   
28        0  32.06292   37.10     80.625     63.5  38.08708  80.500000   
29        0  25.31461   36.55     86.750     68.5  39.83539  83.333333   
..      ...       ...     ...        ...      ...       ...        ...   
77        0  27.95181   36.95     89.500     68.5  40.49819  78.666667   
78        0  27.02738   36.90     88.000     64.5  46.04762  78.333333   
79        0  26.50830   36.50     89.000     62.0  45.09170  69.166667   
80        0  28.04134   37.10     93.000     75.0  44.74728  83.666667   
81        0  15.40250   36.60     77.250     60.5  47.02250  83.166667   
82        1  18.86233   36.55     90.475     62.5  55.63767  77.666667   
83        0  24.49151   37.05     79.125     63.0  42.10849  75.000000   
84        0  26.52392   36.35     94.475     75.0  44.87608  70.666667   
85        1  29.56324   36.40    101.875     60.0  63.23676  82.333333   
86        0  16.93165   36.60     79.375     72.5  47.29335  77.666667   
87        1  19.74082   36.80     89.200     51.0  61.20918  68.833333   
88        1  18.03599   36.65     85.500     54.5  56.66401  68.000000   
89        0  19.21288   36.65     84.000     62.0  40.58712  62.000000   
90        1  19.94891   37.20     89.600     70.5  54.02609  83.000000   
91        1  21.99068   36.65     95.750     67.5  62.75932  76.333333   
92        1  21.98649   36.65     91.625     59.5  63.48851  63.500000   
93        0  29.67915   36.80     95.000     58.5  49.67085  71.666667   
94        0  20.52818   36.75     76.500     54.5  42.39682  62.333333   
95        0  29.85703   36.60     86.125     65.0  39.79297  75.666667   
96        1  26.76094   36.70     98.875     73.5  62.21406  84.000000   
97        0  24.87186   36.85     79.000     68.5  35.77814  63.833333   
98        0  19.12753   37.00     85.125     69.5  44.24747  70.333333   
99       

In [155]:
# prepare configuration for cross validation test harness
seed = 7

In [156]:
# prepare models
models = []
#models.append(('Lr1', LinearRegression()))
models.append(('LR', LogisticRegression()))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC()))
models.append(('RF', RandomForestClassifier()))
models.append(('AB', AdaBoostClassifier()))

In [157]:
# evaluate each model in turn
results = []
names = []
scoring = 'accuracy'
for name, model in models:
	kfold = model_selection.KFold(n_splits=10, random_state=seed)
	cv_results = model_selection.cross_val_score(model, X1, y1, cv=kfold, scoring=scoring)
	results.append(cv_results)
	names.append(name)
	msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
	print(msg)

C:\Users\TENN\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\TENN\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\TENN\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\TENN\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\TENN\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

LR: 0.698182 (0.148813)
LDA: 0.699091 (0.149790)
KNN: 0.653636 (0.197021)
CART: 0.681818 (0.165295)
NB: 0.720000 (0.151728)
SVM: 0.468182 (0.125128)


C:\Users\TENN\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\TENN\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\TENN\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\TENN\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: 

RF: 0.692727 (0.089977)
AB: 0.701818 (0.137017)


In [103]:
kfold

KFold(n_splits=10, random_state=7, shuffle=False)

In [104]:
estimators = [('names', results)]

In [105]:
ensemble = VotingClassifier(estimators, voting = 'hard')

In [106]:
print(ensemble.fit)

<bound method VotingClassifier.fit of VotingClassifier(estimators=[('names',
                              [array([0.63636364, 0.72727273, 0.63636364, 0.72727273, 0.63636364,
       0.54545455, 0.63636364, 0.6       , 0.9       , 0.6       ]),
                               array([0.63636364, 0.90909091, 0.81818182, 0.54545455, 0.63636364,
       0.45454545, 0.54545455, 0.6       , 0.8       , 0.5       ]),
                               array([0.36363636, 0.54545455, 0.72727273, 0.63636364, 0.45454545,
       0.63636364, 0.72727273, 0.7       , 0.8       , 0.4       ]),
                               array([0.45454545...
                               array([0.36363636, 0.36363636, 0.54545455, 0.63636364, 0.54545455,
       0.36363636, 0.45454545, 0.7       , 0.7       , 0.3       ]),
                               array([0.54545455, 0.54545455, 0.63636364, 0.72727273, 0.72727273,
       0.72727273, 0.63636364, 0.7       , 0.7       , 0.5       ]),
                               array

In [14]:
ensemble.fit(X1, y1)

TypeError: Cannot clone object 'array([0.55555556, 0.52777778, 0.6       ])' (type <class 'numpy.ndarray'>): it does not seem to be a scikit-learn estimator as it does not implement a 'get_params' methods.